---
_extends: .github

repository:
  name: js-toxcore-c
  description: Node bindings for toxcore
  topics: toxcore, javascript

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "build (10.x)"
          - "build (12.x)"
          - "build (13.x)"
          - "DeepScan"
          - "security/snyk (TokTok)"
